# Generated by Django 2.2.1 on 2019-05-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0002_auto_20190508_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='site',
            new_name='sites',
        ),
    ]
