# Generated by Django 2.2.1 on 2019-05-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0003_auto_20190508_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sites',
        ),
        migrations.AddField(
            model_name='site',
            name='items',
            field=models.ManyToManyField(to='mainboard.Item'),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='mainboard.Item')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainboard.Site')),
            ],
        ),
    ]
