# Generated by Django 2.2.1 on 2019-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0004_auto_20190508_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='period',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
