# Generated by Django 2.2.1 on 2019-05-12 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0006_auto_20190512_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='config',
        ),
        migrations.AddField(
            model_name='config',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainboard.Site'),
            preserve_default=False,
        ),
    ]
